version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - php --version
      - echo "install something"
  pre_build:
    commands:
      - echo "now we are in pre build phase"
  build:
    commands:
      - echo "now we are in build block"
      - echo "we will run some test"
      - grep -Fq "Main Page" public/index.php
  post_build:
    commands:
      - echo "we are in the post build phase"
